version: "3"
services:
  nginx:
    restart: always
    build:
      context: nginx
    ports:
        - "80:80"
    depends_on:
      - app
    logging:
      driver: "none"


  app:
    restart: always
    build: ./
    ports:
      - "80"
    volumes:
      - .:/app
    links:
      - mongo
    environment:
      - PORT=5000
    deploy:
      mode: replicated
      replicas: 3

  mongo:
    container_name: mongo
    command: mongod --quiet --logpath /dev/null
    volumes:
      - ./database:/data/db
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none

